### ISSUE TITLE
Add unique constraint on a field without permissions

### ISSUE THREAD

**Issue by marktani** [graphcool/dashboard#236] opened 2016-10-01 20:22 UTC
> Got "internal server error" when trying to add a unique constraint on a field which doesn't have any permissions configured.

![untitled](https://cloud.githubusercontent.com/assets/1780597/19016815/4c756278-8825-11e6-98eb-88eaab999e3a.png)

thanks to @sedubois

**Comment by schickling** [comment] 2016-10-02 18:48
This is a backend problem and will be fixed shortly. I'm closing this for now as @sorenbs is taking care of it.

**Closed by schickling** 2016-10-02 18:48 UTC

**Comment by sorenbs** [comment] 2016-10-06 15:28
This was most likely caused by there being duplicates in the column before adding the unique index. @marktani - are you sure this was related to there being no permission?

**Comment by marktani** [comment] 2016-10-06 15:30
@sedubois might know :)

**Comment by sorenbs** [comment] 2016-10-06 15:31
Ahh, didn't see that. Thanks!
